services:
  - type: web
    name: blog-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: db.pieyieohlajfqqohoalk.supabase.co
      - key: DB_USER
        value: postgres
      - key: DB_NAME
        value: postgres
      - key: DB_PORT
        value: "5432"
      - key: DB_PASSWORD
        sync: false
      - key: KEY_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://full-stack-blog-app-zeta.vercel.app
      - key: PORT
        value: 3000

  - type: web
    name: blog-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html